# Information Ret Project

- User is reading about Saching Blogs
- which other posts you can recommed to that person


- Query A- Document A
- Which Docs are sim to Doc A and pass on that as well

In [1]:
import  pandas as pd

In [2]:
people = pd.read_csv('people_data.csv')

In [3]:
people.head()

URI                 name  \
0         <http://dbpedia.org/resource/Bill_Clinton>         Bill Clinton   
1   <http://dbpedia.org/resource/Polyana_L%C3%B3pez>   Polyana L%C3%B3pez   
2        <http://dbpedia.org/resource/Harpdog_Brown>        Harpdog Brown   
3  <http://dbpedia.org/resource/Franz_Rottensteiner>  Franz Rottensteiner   
4               <http://dbpedia.org/resource/G-Enka>               G-Enka   

                                                text  
0  william jefferson bill clinton born william je...  
1  polyana lpez born circa 1985 is an argentine a...  
2  harpdog brown is a singer and harmonica player...  
3  franz rottensteiner born in waidmannsfeld lowe...  
4  henry krvits born 30 december 1974 in tallinn ...

In [4]:
# Replace all Null values with "No Data"
people.fillna('No Data', inplace=True)

# Using TFIDF

In [5]:
# converting our text col to tfidf values

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer()  # you can perform all sorts of pre processing here
X_train_tfidf = tfidf_vect.fit_transform(people.text)

In [6]:
tfidf_vect.get_feature_names()[-5:]

['zzb', 'zzebra', 'zzran', 'zzt', 'zzts']

In [7]:
X_train_tfidf

<59071x548412 sparse matrix of type '<class 'numpy.float64'>'
	with 10244123 stored elements in Compressed Sparse Row format>

In [8]:
people.shape

(59071, 3)

In [9]:
from sklearn.neighbors import NearestNeighbors

In [10]:
nn = NearestNeighbors(n_neighbors=10, p=2) # here you can change value

In [11]:
nn_fitted = nn.fit(X_train_tfidf)

# Find Neighbours

- Amitabh

In [12]:
people.head()

URI                 name  \
0         <http://dbpedia.org/resource/Bill_Clinton>         Bill Clinton   
1   <http://dbpedia.org/resource/Polyana_L%C3%B3pez>   Polyana L%C3%B3pez   
2        <http://dbpedia.org/resource/Harpdog_Brown>        Harpdog Brown   
3  <http://dbpedia.org/resource/Franz_Rottensteiner>  Franz Rottensteiner   
4               <http://dbpedia.org/resource/G-Enka>               G-Enka   

                                                text  
0  william jefferson bill clinton born william je...  
1  polyana lpez born circa 1985 is an argentine a...  
2  harpdog brown is a singer and harmonica player...  
3  franz rottensteiner born in waidmannsfeld lowe...  
4  henry krvits born 30 december 1974 in tallinn ...

In [13]:
index = people[people.name.str.contains("amitabh", case=False)].index[0]
index

48151

In [14]:
X_train_tfidf[index,:] # tfidf vector for Amitabh

<1x548412 sparse matrix of type '<class 'numpy.float64'>'
	with 145 stored elements in Compressed Sparse Row format>

In [15]:
score, neighbours = nn_fitted.kneighbors(X_train_tfidf[index,:])

In [16]:
score[0]

array([0.        , 1.1450037 , 1.14516594, 1.15612104, 1.16326194,
       1.1887013 , 1.1989314 , 1.2017944 , 1.20739367, 1.20792693])

In [17]:
neighbours[0]

array([48151, 23229, 13267, 58790, 25394, 26948,   331, 41897, 50670,
        7504])

In [18]:
people.iloc[neighbours[0]]

URI                name  \
48151    <http://dbpedia.org/resource/Amitabh_Bachchan>    Amitabh Bachchan   
23229         <http://dbpedia.org/resource/Dilip_Kumar>         Dilip Kumar   
13267          <http://dbpedia.org/resource/Aamir_Khan>          Aamir Khan   
58790       <http://dbpedia.org/resource/Jaya_Bachchan>       Jaya Bachchan   
25394            <http://dbpedia.org/resource/Mohanlal>            Mohanlal   
26948         <http://dbpedia.org/resource/Chiranjeevi>         Chiranjeevi   
331             <http://dbpedia.org/resource/Mammootty>           Mammootty   
41897       <http://dbpedia.org/resource/K._J._Yesudas>       K. J. Yesudas   
50670  <http://dbpedia.org/resource/Jasbir_Singh_Bajaj>  Jasbir Singh Bajaj   
7504          <http://dbpedia.org/resource/Rajinikanth>         Rajinikanth   

                                                    text  
48151  amitabh harivansh bachchan ipa mtab bttn born ...  
23229  dilip kumar born muhammad yusuf khan on 11 dec...  
13267  aamir khan pronounced amr xan born mohammed aa...  
58790  jaya bachchan bengali hindi urdu born jaya bha...  
25394  mohanlal viswanathan nair born 21 may 1960 bet...  
26948  chiranjeevi born konidela siva sankara vara pr...  
331    mammootty born as muhammad kutty ismail panipa...  
41897  kattassery joseph yesudas malayalam born 10 ja...  
50670  drjasbir singh bajaj is an indian physician an...  
7504   rajinikanth born shivaji rao gaekwad 12 decemb...

In [19]:
people.name.values

array(['Bill Clinton', 'Polyana L%C3%B3pez', 'Harpdog Brown', ...,
       'David Cass (footballer)', 'Keith Elias', 'Fawaz Damrah'],
      dtype=object)

# Unkown actor example

In [20]:
some_actor = "some text bollywood movie hindi cinema"
unknown_actor = tfidf_vect.transform([some_actor]) # do not use fit_transform

In [21]:
score, neighbours = nn_fitted.kneighbors(unknown_actor)

In [22]:
people.iloc[neighbours[0]]

URI  \
23353           <http://dbpedia.org/resource/Derek_Bose>   
5982          <http://dbpedia.org/resource/Tarun_shienh>   
2065          <http://dbpedia.org/resource/Priyadarshan>   
28702     <http://dbpedia.org/resource/Vageesh_Saraswat>   
20863    <http://dbpedia.org/resource/Vaibhavi_Merchant>   
2390      <http://dbpedia.org/resource/Mumtaz_(actress)>   
19701      <http://dbpedia.org/resource/Gopaldas_Neeraj>   
58840  <http://dbpedia.org/resource/Balendu_Sharma_Da...   
13243    <http://dbpedia.org/resource/Frank_P._Tomasulo>   
9320               <http://dbpedia.org/resource/Sridevi>   

                         name  \
23353              Derek Bose   
5982             Tarun shienh   
2065             Priyadarshan   
28702        Vageesh Saraswat   
20863       Vaibhavi Merchant   
2390         Mumtaz (actress)   
19701         Gopaldas Neeraj   
58840  Balendu Sharma Dadhich   
13243       Frank P. Tomasulo   
9320                  Sridevi   

                                                    text  
23353  derek bose born in calcutta on 15 september 19...  
5982   tarun shienh is among the bestknown poets and ...  
2065   priyadarshan soman nair is an indian film dire...  
28702  vageesh saraswat hindi is a hindi journalist a...  
20863  vaibhavi merchant is an indian dance choreogra...  
2390   mumtaz hindi arabic born 31 july 1947 is an ac...  
19701  gopaldas saxena neeraj popularly known as nira...  
58840  balendu sharma dadhich hindi is an indian tech...  
13243  frank p tomasulo is an american film critic th...  
9320   sridevi kapoor known as sridevi born shree amm...

# Count Vect

In [23]:
# converting our text col to tfidf values

from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_count = count_vect.fit_transform(people.text)

In [24]:
nn_fitted_cv = nn.fit(X_train_count)

In [25]:
score, neighbours = nn_fitted_cv.kneighbors(X_train_count[index,:])

In [26]:
people.iloc[neighbours[0]]

URI  \
48151     <http://dbpedia.org/resource/Amitabh_Bachchan>   
47179            <http://dbpedia.org/resource/Eric_Bana>   
13313       <http://dbpedia.org/resource/Keith_Faulkner>   
22635  <http://dbpedia.org/resource/Thomas_Murphy_(jo...   
50021          <http://dbpedia.org/resource/Irrfan_Khan>   
26371       <http://dbpedia.org/resource/Greg_Cruttwell>   
47703        <http://dbpedia.org/resource/Richard_Leduc>   
24785          <http://dbpedia.org/resource/Ron_Husmann>   
26002   <http://dbpedia.org/resource/Christopher_Walken>   
19971  <http://dbpedia.org/resource/Antonio_Isasi-Isa...   

                             name  \
48151            Amitabh Bachchan   
47179                   Eric Bana   
13313              Keith Faulkner   
22635  Thomas Murphy (journalist)   
50021                 Irrfan Khan   
26371              Greg Cruttwell   
47703               Richard Leduc   
24785                 Ron Husmann   
26002          Christopher Walken   
19971     Antonio Isasi-Isasmendi   

                                                    text  
48151  amitabh harivansh bachchan ipa mtab bttn born ...  
47179  eric bana born eric banadinovi 9 august 1968 i...  
13313  keith faulkner born 25 july 1936 is an english...  
22635  thomas tom murphy is a british born journalist...  
50021  sahabzade irrfan ali khan born 7 january 1967 ...  
26371  greg cruttwell born in 1962 in london is an en...  
47703  richard leduc born 1941 is a french actor he a...  
24785  ron husmann born june 30 1937 is an american a...  
26002  christopher walken born ronald walken on march...  
19971  antonio isasiisasmendi born 22 march 1927 is a...

# Lets understand NN algo

### NearestNeighbors()

- metric='minkowski'
- p=2 ( default value is 2 )

## minkowski distance algo

- manhattan distance
- euclidian distance

In [27]:
# Manhattan Distance
x = [1,0,0]
y = [0,1,0]

distance = 0

for i,j in zip(x,y):
    distance += abs(i-j)

print(distance)

2


In [28]:
# euclidian distance
x = [1,0,0]
y = [0,1,0]

distance = 0

for i,j in zip(x,y):
    distance += abs((i-j)) ** 2

distance = distance ** (1/2)
print(distance)

1.4142135623730951


In [29]:
# minkowski - function - generic function
x = [1,0,0]
y = [0,1,0]
p = 5
distance = 0

for i,j in zip(x,y):
    distance += abs((i-j)) ** p

distance = distance ** (1/p)
print(distance)

1.148698354997035


# Clustering

<img src='./clustering.png'/>

# Clustering using Sklearn


- twitter data set - to concrete your understanding

In [30]:
people = pd.read_csv('people_data.csv', nrows=100)

In [31]:
from sklearn.cluster import KMeans

In [32]:
tfidf_vect = TfidfVectorizer()
X_train_tfidf = tfidf_vect.fit_transform(people.text)

In [33]:
X_train_tfidf.shape

(100, 6981)

In [34]:
kmeans = KMeans(n_clusters=2).fit(X_train_tfidf)

In [35]:
kmeans.cluster_centers_

array([[0.00446825, 0.00249195, 0.        , ..., 0.        , 0.        ,
        0.0079205 ],
       [0.00456433, 0.00350472, 0.00047163, ..., 0.00061521, 0.00089161,
        0.        ]])

In [36]:
kmeans.labels_

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int32)

# import twitter data

perform clustering

# How to use tfidf instance in test.py and train.py

- train.py - tfidf - fit_transform
- test.py - tftidf - transform

## method 1 -save  the features
1. Save features in a csv file while training
2. While test.py executes - `TfidfVectorizer(vocabulary=[])`


## method 2 - pickle 
1. Save the tfidf variable in a file while training
2. Load the same variable while test.py executes